import type { Metadata } from "next";
import { Aboreto, Poppins } from "next/font/google";
import "../styles/globals.css";
import requestGraphQl from "@/utils/graphQL/graphQLClient";
import { MainMenu } from "@/utils/types";
import { mainMenuQuery } from "@/utils/helpers";
import Header from "@/components/Layout/Header";

const aboreto = Aboreto({
  variable: "--font-aboreto",
  weight: "400",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await requestGraphQl<{
    acfOptionsMainMenu: MainMenu;
  }>(mainMenuQuery());
  return (
    <html lang="en">
      <body
        className={`${aboreto.variable} ${poppins.variable} font-body antialiased`}
      >
        <Header menuData={data?.acfOptionsMainMenu} />
        {children}
      </body>
    </html>
  );
}
